[book]
title = "應該是 Profilling 吧？"
authors = ["Codex"]
language = "zh-TW"
multilingual = false
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = ""
